### ISSUE TITLE
set-face-attribute: Wrong type argument: stringp, black

### ISSUE THREAD

**Issue by michael-heerdegen** [wasamasa/gotham-theme#13] opened 2015-04-21 13:34 UTC
Hello,

this error occurred after upgrading the Melpa package today and restarting Emacs with my config.

Here is a recipe for emacs -q:

emacs -q
(package-initialize)
(load-theme 'gotham)
M-x term RET

==> Wrong type argument: stringp, black

Thanks,

Michael.

**Comment by wasamasa** [comment] 2015-04-21 13:42
Hmm, cannot reproduce that here. Could you include your Emacs build and version, operating system and a full backtrace?

**Comment by wasamasa** [comment] 2015-04-21 13:54
Should be fixed now in the next MELPA release. Thanks for the report, wouldn't have catched it otherwise :+1:

**Closed** 2015-04-21 13:54 UTC

**Comment by michael-heerdegen** [comment] 2015-04-22 10:44
Vasilij Schneidermann <notifications@github.com> writes:

> Should be fixed now in the next MELPA release.

Yip, I can confirm that it's fixed - thanks!
