### ISSUE TITLE
When using Gotham in iTerm2 with Gotham for Emacs, cursor disappears.

### ISSUE THREAD

**Issue by hahuang65** [wasamasa/gotham-theme#15] opened 2015-05-22 00:03 UTC
When using your theme along with the Gotham theme for the terminal, the cursor completely disappears.

If I switch my theme in terminal to something else, then the cursor will be visible. I think there's some clash of colors or something.

Ever seen this before?

**Comment by hahuang65** [comment] 2015-05-22 00:08
Unchecking "Smart Cursor Color" option in iTerm fixes it.

**Comment by hahuang65** [comment] 2015-05-22 00:10
Sorry, false alarm. It's still broken. But it looks like it's working outside of tmux, but fails in tmux.

**Comment by wasamasa** [comment] 2015-05-22 05:18
Well, that's weird. Works for me here on Linux with Termite, both within and outside tmux. I'll see whether I can get it reproduced on a Mac at work.

As for whether I did see such a thing before, yes, I had this once for Solarized Dark, the Emacs daemon and Evil. The cursor was visible, but did disappear in regions as both the region and the cursor had the same color and this caused them to cancel each other out somehow.  I did later find out that one of the wildcard lines in `.Xresources` did have an unexpected effect for the daemon only and that reloading themes made it disappear. I did eventually get rid of color settings in it completely as I'm rarely using Emacs in the terminal.

**Comment by wasamasa** [comment] 2015-05-22 05:49
Just went through my backlog to find this:

```
<hahuang65> [01:42:56] hey guys, my cursor disappeared in my emacs for some reason... Has anyone experienced this before?
<anxt> [01:47:30] hahuang65, xorg or console?
<hahuang65> [01:49:18] anxt: terminal, iTerm2 to be exact. it's xterm-256color
<anxt> [01:49:56] oh, I wonder if your terminal got a funny escape code
<anxt> [01:50:18] you might try Ctrl-Z; reset; fg
<anxt> [01:50:38] or just exit emacs and see if the cursor is still missing
<anxt> [01:50:49] it happens to me all the time when I cat binary to the screen
<hahuang65> [01:51:19] anxt: nope, it's only missing in emacs. No matter what theme I use, and I even commented out my cursor settings.
<anxt> [01:51:35] hmm, I got nothing for you then.
<hahuang65> [01:51:57] anxt: :(
<anxt> [01:52:00] maybe you could export a different term type
<anxt> [01:52:09] like rxvt
<hahuang65> [02:00:47] anxt: it seems like... it's a conflict between my terminal theme and my emacs theme (they both are the same)
<hahuang65> [02:00:55] but when I swithc my terminal theme, I can see the cursor lol.
<hahuang65> [02:01:07] someone didn't try it out when making the themes :p
<anxt> [02:01:50] interesting
<hahuang65> [02:03:26] :\ filed a ticket for the theme maintainer :)
<hahuang65> [02:03:30] anxt: thanks for your help!
<anxt> [02:03:42] np
<hahuang65> [02:12:05] hmm interesting. It happens in tmux, but not in regular terminal...
<hahuang65> [02:13:02] anxt: hehe foudn it: https://gitlab.com/gnachman/iterm2/issues/3539
<anxt> [02:18:10] i dunno iterm2
<anxt> [02:18:24] most of my shit doesn't start with an i cause I have a lenovo
<hahuang65> [02:18:55] hehe it's not iterm2 it turns out.
<hahuang65> [02:19:17] anxt: it's tmux 2.0 which was recently released. Supposedly it's fixed in master, but htat's not release in my package manager yet :
<hahuang65> [02:19:39] anxt: just FYI, in case anyone else asks and you reply to try to help :)
<anxt> [02:19:49] ok cool
<anxt> [02:19:59] I am going to go home my ass has been sat on too much today
<anxt> [02:20:17] so I am going to go lay on my side and watch TV
<hahuang65> [02:21:13] haha awesome
<anxt> [02:21:36] all day C++ threading and debugging
<anxt> [02:21:44] my brain feels dazed
<hahuang65> [02:21:46] i feel you
```

So, this issue could resolve itself once you have a more recent version of tmux installed? Which of the available package managers are you using on OS X? If it's [brew](http://brew.sh/), it should be simple to verify as it comes with the option to build from more up-to-date sources for most stuff.

**Comment by hahuang65** [comment] 2015-05-22 17:56
Yup, there are reports that building tmux from master will fix it up.

I'll wait for the brew package to be released, and I'll let you know if it fixes it! :) Thanks!

**Comment by wasamasa** [comment] 2015-05-22 19:36
It should be sufficient to use `brew install --HEAD tmux` to grab the development version and check whether it's been fixed, otherwise you'll be waiting for the next stable release (which could take a lot longer).

**Comment by hahuang65** [comment] 2015-05-22 20:28
Just tried it and it did not work unfortunately :( What would be a good next step?

**Comment by wasamasa** [comment] 2015-05-22 21:34
I'll see after attempting reproduction on an OS X machine. While you're at it, what's your Emacs version and build (where did you grab it from?)?

**Comment by hahuang65** [comment] 2015-05-22 21:35
Emacs GNU Emacs 24.5.1
Got it from homebrew.

**Comment by hahuang65** [comment] 2015-05-29 23:15
So people have been reporting that installing tmux from master is working:
https://bbs.archlinux.org/viewtopic.php?id=197401

This was not the case for me.

Some people here have determined that it's a tmux issue rather than an iTerm 2 issue:
https://gitlab.com/gnachman/iterm2/issues/3539

I've downgraded to tmux 1.9 and it's working brilliantly. I'll try upgrade tmux again when it's 2.1 and see if it's fixed then.

**Comment by wasamasa** [comment] 2015-06-08 09:05
Closing as this isn't really theme-related.

**Closed by wasamasa** 2015-06-08 09:05 UTC
